version: '3.6'

services:
  todo-app:
    build: .
    container_name: "todo-app"
    depends_on:
      - db
    environment:
      DB_URL: postgresql://test:test@db:5432/test
    ports:
      - 8080:8080
    command: python3 server.py --host="0.0.0.0"
    restart: always

  db:
    container_name: "todo-db"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./db_set_up/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql